[general]
project_name = "{timestamp}_morph_blobs_v1_epoch{morph.parameters.train_epochs}_mpsz{morph.parameters.mp_sz}_wrp{morph.parameters.warp_scale}_af{morph.parameters.add_first}"

[morph]
specifications = "DiffMorph/data/grating_design_specifications.txt"
positions = "DiffMorph/data/grating_position.txt"
optimized_dir = "DiffMorph/data/results_freeform_final_new"
image_name = "mat_props.png"
scale = 0.003
thresholds = [60, 90, 127, 150]

[morph.parameters]
train_epochs = 200
# im_sz = 1024
mp_sz = 96
warp_scale = 0.05
mult_scale = 0.4
add_scale = 0.4
add_first = false
